[build]
  base = "webIntegration"
  command = "npm run build"
  publish = "webIntegration/.next"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
